// Port of Ambermoon.Data.Common/CursorType.cs from Ambermoon.net (GPL-3.0, Copyright (C) Robert Schneckenhaus)
export const CursorType = Object.freeze({
	None: -1,
	Sword: 0,
	ArrowUp: 1,
	ArrowDown: 2,
	ArrowLeft: 3,
	ArrowRight: 4,
	ArrowUpLeft: 5,
	ArrowUpRight: 6,
	ArrowDownLeft: 7,
	ArrowDownRight: 8,
	ArrowForward: 9,
	ArrowBackward: 10,
	ArrowStrafeLeft: 11,
	ArrowStrafeRight: 12,
	ArrowTurnLeft: 13,
	ArrowTurnRight: 14,
	ArrowRotateLeft: 15,
	ArrowRotateRight: 16,
	Wait: 17,
	Eye: 18,
	Mouth: 19,
	Disk: 20,
	Gold: 21,
	Food: 22,
	SmallArrow: 23,
	Hand: 24,
	Target: 25,
	Click: 26,
	VideoWait: 27,
});
