// Port of Ambermoon.Data.Common/Enumerations/Song.cs from Ambermoon.net (GPL-3.0, Copyright (C) Robert Schneckenhaus)

export const Song = Object.freeze({
	Default: 0,
	WhoSaidHiHo: 1,
	MellowCamelFunk: 2,
	CloseToTheHedge: 3,
	VoiceOfTheBagpipe: 4,
	Downtown: 5,
	Ship: 6,
	WholeLottaDove: 7,
	HorseIsNoDisgrace: 8,
	DontLookBach: 9,
	RoughWaterfrontTavern: 10,
	SapphireFireballsOfPureLove: 11,
	TheAumRemainsTheSame: 12,
	Capital: 13,
	PloddingAlong: 14,
	CompactDisc: 15,
	RiversideTravellingBlues: 16,
	NobodysVaultButMine: 17,
	LaCryptaStrangiato: 18,
	MistyDungeonHop: 19,
	BurnBabyBurn: 20,
	BarBrawlin: 21,
	PsychedelicDuneGroove: 22,
	StairwayToLevel50: 23,
	ThatHunchIsBack: 24,
	ChickenSoup: 25,
	DragonChaseInCreepyDungeon: 26,
	HisMastersVoice: 27,
	NoName: 28,
	OhNoNotAnotherMagicalEvent: 29,
	TheUhOhSong: 30,
	OwnerOfALonelySword: 31,
	GameOver: 32,
	Intro: 33,
	Outro: 34,
	Menu: 35
});
